owner: North-Star-AGI
repo: etoile-status
user-agent: North-Star-AGI

sites:
  - name: Etoile Website
    url: https://etoile.events
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Etoile API
    url: https://etoile-api.fly.dev/health
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200

assignees:
  - seifeldinismail

status-website:
  baseUrl: /etoile-status
  logoUrl: https://etoile.events/etoile.png
  favicon: https://etoile.events/etoile.png
  name: Etoile Status
  introTitle: "**Etoile** Service Status"
  introMessage: >
    Real-time status for all Etoile services.
    [Visit Etoile](https://etoile.events)
  navbar:
    - title: Etoile
      href: https://etoile.events
  theme: dark
  css: |
    /* ===== Etoile Brand Theme ===== */

    /* --- Core Variables --- */
    :root {
      --body-background-color: #0a0a0a;
      --body-text-color: #f0f0f0;
      --card-background-color: #111111;
      --nav-background-color: #0a0a0a;
      --nav-border-bottom-color: rgba(255, 255, 255, 0.08);
    }

    /* --- Typography --- */
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      letter-spacing: -0.01em;
    }

    /* --- Links --- */
    a { color: #ff7f50; transition: color 0.2s ease; }
    a:hover { color: #ff9a76; }

    /* --- Navigation --- */
    nav {
      padding: 1rem 2rem;
      border-bottom: 1px solid rgba(255, 255, 255, 0.06);
      backdrop-filter: blur(12px);
      -webkit-backdrop-filter: blur(12px);
    }
    nav a {
      color: rgba(255, 255, 255, 0.7);
      font-weight: 500;
      font-size: 0.875rem;
      padding: 0.5rem 1rem;
      border-radius: 8px;
      transition: all 0.2s ease;
    }
    nav a:hover {
      color: #ffffff;
      background: rgba(255, 255, 255, 0.05);
    }
    nav a[aria-current="page"] {
      color: #ff7f50;
      background: rgba(255, 127, 80, 0.08);
    }
    nav img.logo {
      height: 28px;
      width: auto;
      border-radius: 6px;
    }

    /* --- Header / Intro --- */
    header {
      margin-bottom: 2.5rem;
      padding-top: 1rem;
    }
    header h1 {
      color: #ffffff;
      font-size: 1.75rem;
      font-weight: 700;
      letter-spacing: -0.03em;
    }
    header h1 strong { color: #ff7f50; }
    header p.lead {
      color: rgba(255, 255, 255, 0.5);
      font-size: 0.95rem;
      font-weight: 400;
      line-height: 1.6;
    }
    header p.lead a { color: #ff7f50; text-decoration: none; }
    header p.lead a:hover { text-decoration: underline; }

    /* --- Time Period Radio Buttons --- */
    .f.r {
      gap: 0.375rem;
      margin-bottom: 1.5rem;
    }
    .f.r label {
      background: rgba(255, 255, 255, 0.04);
      border: 1px solid rgba(255, 255, 255, 0.08);
      border-radius: 8px;
      padding: 0.375rem 0.875rem;
      font-size: 0.8rem;
      font-weight: 500;
      color: rgba(255, 255, 255, 0.5);
      cursor: pointer;
      transition: all 0.2s ease;
    }
    .f.r label:hover {
      background: rgba(255, 255, 255, 0.06);
      border-color: rgba(255, 255, 255, 0.15);
      color: rgba(255, 255, 255, 0.8);
    }
    .f.r input[type="radio"]:checked + label,
    .f.r label:has(input:checked) {
      background: rgba(255, 127, 80, 0.1);
      border-color: rgba(255, 127, 80, 0.3);
      color: #ff7f50;
    }

    /* --- Status Cards (article.graph) --- */
    article {
      background: #111111;
      border: 1px solid rgba(255, 255, 255, 0.06);
      border-radius: 14px;
      padding: 1.25rem 1.5rem;
      margin-bottom: 0.75rem;
      transition: border-color 0.2s ease, background 0.2s ease;
    }
    article:hover {
      border-color: rgba(255, 255, 255, 0.12);
      background: #141414;
    }
    article a {
      color: #ffffff;
      font-weight: 600;
      font-size: 0.95rem;
      text-decoration: none;
    }
    article a:hover { color: #ff7f50; }

    /* Site icon in status cards */
    article .icon, article img[src*="duckduckgo"] {
      height: 20px;
      width: 20px;
      border-radius: 4px;
      margin-right: 0.5rem;
    }

    /* --- Data Badges (uptime %, response time) --- */
    .data {
      background: rgba(255, 255, 255, 0.04);
      border: 1px solid rgba(255, 255, 255, 0.08);
      border-radius: 8px;
      padding: 0.25rem 0.75rem;
      font-size: 0.8rem;
      font-weight: 600;
      color: rgba(255, 255, 255, 0.85);
      transition: all 0.3s ease;
    }

    /* --- Graph Images --- */
    article.graph {
      background-size: cover;
      background-position: center;
      border-radius: 14px;
      overflow: hidden;
    }
    section canvas,
    section img[src*="graph"] {
      border-radius: 10px;
      opacity: 0.85;
    }

    /* --- Incident Cards --- */
    article.down {
      border-left: 3px solid #ef4444;
    }
    article.degraded {
      border-left: 3px solid #f59e0b;
    }
    article.down a, article.degraded a {
      color: #ffffff;
    }

    /* --- Section Headings (Past Incidents, Scheduled, etc.) --- */
    h2 {
      color: rgba(255, 255, 255, 0.9);
      font-size: 1.1rem;
      font-weight: 600;
      letter-spacing: -0.02em;
      margin-top: 2.5rem;
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid rgba(255, 255, 255, 0.06);
    }

    /* --- Active Incident Banner --- */
    article.down:not(.link) {
      background: rgba(239, 68, 68, 0.06);
      border: 1px solid rgba(239, 68, 68, 0.2);
    }

    /* --- Footer --- */
    footer {
      margin-top: 3rem;
      padding: 1.5rem 0;
      border-top: 1px solid rgba(255, 255, 255, 0.06);
      opacity: 0.4;
      font-size: 0.8rem;
    }
    footer a { color: rgba(255, 255, 255, 0.5); }
    footer a:hover { color: #ff7f50; }

    /* --- Container --- */
    main, .container {
      max-width: 720px;
      margin: 0 auto;
      padding: 0 1.5rem;
    }

    /* --- Scrollbar (dark theme) --- */
    ::-webkit-scrollbar { width: 6px; }
    ::-webkit-scrollbar-track { background: #0a0a0a; }
    ::-webkit-scrollbar-thumb {
      background: rgba(255, 255, 255, 0.15);
      border-radius: 3px;
    }
    ::-webkit-scrollbar-thumb:hover { background: rgba(255, 255, 255, 0.25); }

    /* --- Loading Spinner --- */
    .loading { opacity: 0.4; }

    /* --- Responsive --- */
    @media (max-width: 640px) {
      header h1 { font-size: 1.4rem; }
      article { padding: 1rem; }
      nav { padding: 0.75rem 1rem; }
    }
  links:
    - rel: preconnect
      href: https://fonts.googleapis.com
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  updates: "0 0 * * *"
  graphs: "0 0 * * *"
  staticSite: "0 0 * * *"
