owner: North-Star-AGI
repo: etoile-status
user-agent: North-Star-AGI

sites:
  - name: Etoile Website
    url: https://etoile.events
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Etoile API
    url: https://etoile-api.fly.dev/health
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200

  - name: Etoile API (Server)
    url: https://etoile-api.fly.dev/
    maxResponseTime: 3000
    expectedStatusCodes:
      - 200

  - name: Etoile Events API
    url: https://etoile-api.fly.dev/api/v1/events?limit=1
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Etoile Embed API
    url: https://etoile-api.fly.dev/api/v1/embed/events?limit=1
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

  - name: Etoile Search
    url: https://etoile-api.fly.dev/api/v1/search?q=test
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

assignees:
  - seifeldinismail

status-website:
  baseUrl: /etoile-status
  favicon: https://etoile.events/etoile.png
  name: ""
  introTitle: ""
  introMessage: ""
  navbar: []
  theme: dark
  css: |
    /* ===== Etoile Embedded Status Theme ===== */
    /* Matches etoile-frontend dark theme: oklch(0.2 0 0) bg, oklch(0.24 0 0) cards */

    :root {
      --body-background-color: #272727;
      --body-text-color: #fafafa;
      --card-background-color: #313131;
      --nav-background-color: #272727;
      --nav-border-bottom-color: transparent;
    }

    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      letter-spacing: -0.01em;
      font-feature-settings: "kern", "liga", "calt";
    }

    /* --- Hide header & nav (embedded, parent handles branding) --- */
    nav { display: none !important; }
    header { display: none !important; }

    /* --- Links --- */
    a { color: #d4784a; transition: color 0.2s ease; }
    a:hover { color: #e08a5c; }

    /* --- Time Period Radio Buttons --- */
    .f.r {
      gap: 0.375rem;
      margin-bottom: 1.5rem;
    }
    .f.r label {
      background: rgba(255, 255, 255, 0.04);
      border: 1px solid rgba(255, 255, 255, 0.2);
      border-radius: 8px;
      padding: 0.375rem 0.875rem;
      font-size: 0.8rem;
      font-weight: 500;
      color: rgba(255, 255, 255, 0.5);
      cursor: pointer;
      transition: all 0.2s ease;
    }
    .f.r label:hover {
      background: rgba(255, 255, 255, 0.06);
      border-color: rgba(255, 255, 255, 0.3);
      color: rgba(255, 255, 255, 0.8);
    }
    .f.r input[type="radio"]:checked + label,
    .f.r label:has(input:checked) {
      background: rgba(212, 120, 74, 0.1);
      border-color: rgba(212, 120, 74, 0.3);
      color: #d4784a;
    }

    /* --- Status Cards --- */
    article {
      background: #313131;
      border: 1px solid rgba(255, 255, 255, 0.2);
      border-radius: 10px;
      padding: 1.25rem 1.5rem;
      margin-bottom: 0.75rem;
      transition: border-color 0.2s ease, background 0.2s ease;
    }
    article:hover {
      border-color: rgba(255, 255, 255, 0.3);
      background: #383838;
    }
    article a {
      color: #fafafa;
      font-weight: 600;
      font-size: 0.95rem;
      text-decoration: none;
    }
    article a:hover { color: #d4784a; }

    article .icon, article img[src*="duckduckgo"] {
      height: 20px;
      width: 20px;
      border-radius: 4px;
      margin-right: 0.5rem;
    }

    /* --- Data Badges --- */
    .data {
      background: rgba(255, 255, 255, 0.04);
      border: 1px solid rgba(255, 255, 255, 0.2);
      border-radius: 8px;
      padding: 0.25rem 0.75rem;
      font-size: 0.8rem;
      font-weight: 600;
      color: rgba(255, 255, 255, 0.85);
      transition: all 0.3s ease;
    }

    /* --- Graphs --- */
    article.graph {
      background-size: cover;
      background-position: center;
      border-radius: 10px;
      overflow: hidden;
    }
    section canvas,
    section img[src*="graph"] {
      border-radius: 8px;
      opacity: 0.85;
    }

    /* --- Incidents --- */
    article.down {
      border-left: 3px solid #ef4444;
    }
    article.degraded {
      border-left: 3px solid #f59e0b;
    }
    article.down:not(.link) {
      background: rgba(239, 68, 68, 0.08);
      border: 1px solid rgba(239, 68, 68, 0.25);
    }

    /* --- Section Headings --- */
    h2 {
      color: rgba(255, 255, 255, 0.9);
      font-size: 1.1rem;
      font-weight: 600;
      letter-spacing: -0.02em;
      margin-top: 2.5rem;
      margin-bottom: 1rem;
      padding-bottom: 0.5rem;
      border-bottom: 1px solid rgba(255, 255, 255, 0.2);
    }

    /* --- Footer --- */
    footer {
      margin-top: 3rem;
      padding: 1.5rem 0;
      border-top: 1px solid rgba(255, 255, 255, 0.2);
      opacity: 0.4;
      font-size: 0.8rem;
    }
    footer a { color: rgba(255, 255, 255, 0.5); }
    footer a:hover { color: #d4784a; }

    /* --- Container --- */
    main, .container {
      max-width: 720px;
      margin: 0 auto;
      padding: 0 1.5rem;
    }

    /* --- Scrollbar --- */
    ::-webkit-scrollbar { width: 6px; }
    ::-webkit-scrollbar-track { background: rgba(255, 255, 255, 0.03); }
    ::-webkit-scrollbar-thumb {
      background: rgba(255, 255, 255, 0.15);
      border-radius: 4px;
    }
    ::-webkit-scrollbar-thumb:hover { background: rgba(255, 255, 255, 0.25); }

    .loading { opacity: 0.4; }

    @media (max-width: 640px) {
      article { padding: 1rem; }
    }
  links:
    - rel: preconnect
      href: https://fonts.googleapis.com
    - rel: stylesheet
      href: https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  updates: "0 0 * * *"
  graphs: "0 */6 * * *"
  staticSite: "0 */6 * * *"
